# packages in environment at /Users/anshavikhannas/anaconda3/envs/Tensorflow:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0  
_tflow_select             2.2.0                     eigen  
abseil-cpp                20211102.0           he9d5cce_0  
absl-py                   1.4.0           py310hecd8cb5_0  
aiohttp                   3.8.5           py310h6c40b1e_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
anyio                     3.5.0           py310hecd8cb5_0  
appnope                   0.1.2           py310hecd8cb5_1001  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py310hca72f7f_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
astunparse                1.6.3                      py_0  
async-timeout             4.0.2           py310hecd8cb5_0  
attrs                     23.1.0          py310hecd8cb5_0  
babel                     2.11.0          py310hecd8cb5_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.12.2          py310hecd8cb5_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.6.2           py310hecd8cb5_0  
bottleneck                1.3.5           py310h4e76f89_0  
brotli                    1.0.9                hca72f7f_7  
brotli-bin                1.0.9                hca72f7f_7  
brotli-python             1.0.9           py310he9d5cce_7  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.19.1               h6c40b1e_0  
ca-certificates           2023.08.22           hecd8cb5_0  
cachetools                4.2.2              pyhd3eb1b0_0  
cairo                     1.16.0               h3ce6f7e_5  
certifi                   2023.7.22       py310hecd8cb5_0  
cffi                      1.15.1          py310h6c40b1e_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py310hecd8cb5_0  
comm                      0.1.2           py310hecd8cb5_0  
contourpy                 1.0.5           py310haf03e11_0  
cryptography              41.0.3          py310ha2381d6_0  
cvzone                    1.5.6                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
datasets                  2.19.1                   pypi_0    pypi
debugpy                   1.6.7           py310hcec6c5f_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
dill                      0.3.8                    pypi_0    pypi
eigen                     3.3.7                haf03e11_1  
einops                    0.6.1                    pypi_0    pypi
entrypoints               0.4             py310hecd8cb5_0  
exceptiongroup            1.0.4           py310hecd8cb5_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.5.0                hcec6c5f_0  
ffmpeg                    4.2.2                h97e5cf8_0  
filelock                  3.12.0                   pypi_0    pypi
flatbuffers               2.0.0                h23ab428_0  
fontconfig                2.14.1               hb0a0c50_2  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               hd8bbffd_0  
frozenlist                1.3.3           py310h6c40b1e_0  
fsspec                    2024.3.1                 pypi_0    pypi
future                    0.18.3          py310hecd8cb5_0  
gast                      0.4.0              pyhd3eb1b0_0  
gettext                   0.21.0               he85b6c0_1  
giflib                    5.2.1                h6c40b1e_3  
glib                      2.69.1               hfff2838_2  
gmp                       6.2.1                he9d5cce_3  
gmpy2                     2.1.2           py310hd5de756_0  
gnutls                    3.6.15               hed9c0bf_0  
google-auth               2.22.0          py310hecd8cb5_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
google-pasta              0.2.0              pyhd3eb1b0_0  
graphite2                 1.3.14               he9d5cce_1  
grpc-cpp                  1.46.1               h64d96ca_1  
grpcio                    1.42.0                   pypi_0    pypi
gst-plugins-base          1.14.1               hcec6c5f_1  
gstreamer                 1.14.1               h6c40b1e_1  
h5py                      3.7.0           py310h6c517f8_0  
harfbuzz                  4.3.0                hffc734d_1  
hdf5                      1.10.6               h10fe05b_1  
huggingface-hub           0.23.0                   pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      3.4             py310hecd8cb5_0  
install                   1.3.5                    pypi_0    pypi
ipykernel                 6.25.0          py310h20db666_0  
ipympl                    0.8.7              pyhd3eb1b0_0  
ipython                   8.15.0          py310hecd8cb5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
jedi                      0.18.1          py310hecd8cb5_1  
jinja2                    3.1.2           py310hecd8cb5_0  
joblib                    1.2.0           py310hecd8cb5_0  
jpeg                      9e                   h6c40b1e_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.17.3          py310hecd8cb5_0  
jupyter                   1.0.0           py310hecd8cb5_8  
jupyter_client            8.1.0           py310hecd8cb5_0  
jupyter_console           6.6.3           py310hecd8cb5_0  
jupyter_core              5.3.0           py310hecd8cb5_0  
jupyter_events            0.6.3           py310hecd8cb5_0  
jupyter_server            2.5.0           py310hecd8cb5_0  
jupyter_server_terminals  0.4.4           py310hecd8cb5_1  
jupyterlab                3.5.3           py310hecd8cb5_0  
jupyterlab_launcher       0.13.1                     py_2  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.22.0          py310hecd8cb5_0  
jupyterlab_widgets        3.0.5           py310hecd8cb5_0  
keras                     2.12.0                   pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.4.4           py310hcec6c5f_0  
krb5                      1.19.4               hdba6334_0  
lame                      3.100                h1de35cc_0  
lcms2                     2.12                 hf1fd2bf_0  
lerc                      3.0                  he9d5cce_0  
libbrotlicommon           1.0.9                hca72f7f_7  
libbrotlidec              1.0.9                hca72f7f_7  
libbrotlienc              1.0.9                hca72f7f_7  
libclang                  16.0.0                   pypi_0    pypi
libclang13                14.0.6          default_habbcc1a_1  
libcurl                   7.88.1               ha585b31_0  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.17                 hb664fd8_1  
libedit                   3.1.20221030         h6c40b1e_0  
libev                     4.33                 h9ed2024_1  
libffi                    3.4.4                hecd8cb5_0  
libgfortran               5.0.0           11_3_0_hecd8cb5_28  
libgfortran5              11.3.0              h9dfd629_28  
libiconv                  1.16                 hca72f7f_2  
libidn2                   2.3.4                h6c40b1e_0  
libllvm14                 14.0.6               h91fad77_3  
libnghttp2                1.52.0               h1c88b7d_1  
libopenblas               0.3.21               h54e7dc3_0  
libopencv                 4.6.0                hecd8cb5_3  
libopus                   1.3.1                h1de35cc_0  
libpng                    1.6.39               h6c40b1e_0  
libpq                     12.9                 h1c9f633_3  
libprotobuf               3.20.3               hfff2838_0  
libsodium                 1.0.18               h1de35cc_0  
libssh2                   1.10.0               hdb2fb19_2  
libtasn1                  4.19.0               h6c40b1e_0  
libtiff                   4.5.1                hcec6c5f_0  
libunistring              0.9.10               h9ed2024_0  
libuv                     1.44.2               h6c40b1e_0  
libvpx                    1.7.0                h378b8a2_0  
libwebp                   1.3.2                hf6ce154_0  
libwebp-base              1.3.2                h6c40b1e_0  
libxgboost                1.7.3                hcec6c5f_0  
libxml2                   2.10.4               h930c0e2_0  
libxslt                   1.1.37               h6d1eb0e_0  
llvm-openmp               14.0.6               h0dcd299_0  
llvmlite                  0.40.1rc1                pypi_0    pypi
lxml                      4.9.3           py310h946e0e5_0  
lz4-c                     1.9.4                hcec6c5f_0  
markdown                  3.4.1           py310hecd8cb5_0  
markupsafe                2.1.1           py310hca72f7f_0  
matplotlib                3.7.1           py310hecd8cb5_1  
matplotlib-base           3.7.1           py310ha533b9c_1  
matplotlib-inline         0.1.6           py310hecd8cb5_0  
mediapipe                 0.9.1.0                  pypi_0    pypi
mistune                   0.8.4           py310hca72f7f_1000  
ml-dtypes                 0.1.0                    pypi_0    pypi
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.2           py310hca72f7f_0  
multiprocess              0.70.16                  pypi_0    pypi
munkres                   1.1.4                      py_0  
nbclassic                 0.5.5           py310hecd8cb5_0  
nbclient                  0.5.13          py310hecd8cb5_0  
nbconvert                 6.5.4           py310hecd8cb5_0  
nbformat                  5.9.2           py310hecd8cb5_0  
ncurses                   6.4                  hcec6c5f_0  
nest-asyncio              1.5.6           py310hecd8cb5_0  
nettle                    3.7.3                h230ac6f_1  
networkx                  3.1                      pypi_0    pypi
ninja                     1.10.2               hecd8cb5_5  
ninja-base                1.10.2               haf03e11_5  
nltk                      3.7                pyhd3eb1b0_0  
notebook                  6.5.3           py310hecd8cb5_0  
notebook-shim             0.2.2           py310hecd8cb5_0  
nspr                      4.35                 hcec6c5f_0  
nss                       3.89.1               hcec6c5f_0  
numba                     0.57.0                   pypi_0    pypi
numexpr                   2.8.7           py310hf6dca73_0  
numpy                     1.26.0          py310hf6dca73_0  
numpy-base                1.26.0          py310hd8f4981_0  
oauthlib                  3.2.2           py310hecd8cb5_0  
opencv                    4.6.0           py310h3ea8b11_3  
opencv-contrib-python     4.7.0.72                 pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openh264                  2.1.1                h8346a28_0  
openjpeg                  2.4.0                h66ea3da_0  
openssl                   1.1.1w               hca72f7f_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
packaging                 23.1            py310hecd8cb5_0  
pandas                    1.5.3           py310h3ea8b11_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre                      8.45                 h23ab428_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.0.1          py310h7d39338_0  
pip                       23.3            py310hecd8cb5_0  
pixman                    0.40.0               h9ed2024_1  
platformdirs              3.10.0          py310hecd8cb5_0  
plotly                    5.9.0           py310hecd8cb5_0  
ply                       3.11            py310hecd8cb5_0  
prometheus_client         0.14.1          py310hecd8cb5_0  
prompt-toolkit            3.0.36          py310hecd8cb5_0  
prompt_toolkit            3.0.36               hd3eb1b0_0  
protobuf                  3.20.3          py310hcec6c5f_0  
psutil                    5.9.0           py310hca72f7f_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-xgboost                1.7.3           py310hecd8cb5_0  
pyarrow                   16.1.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycocotools               2.0.6                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.15.1          py310hecd8cb5_1  
pyjwt                     2.4.0           py310hecd8cb5_0  
pyopenssl                 23.2.0          py310hecd8cb5_0  
pyparsing                 3.0.9           py310hecd8cb5_0  
pyqt                      5.15.7          py310he9d5cce_0  
pyqt5-sip                 12.11.0                  pypi_0    pypi
pyrsistent                0.18.0          py310hca72f7f_0  
pysocks                   1.7.1           py310hecd8cb5_0  
python                    3.10.10              h218abb5_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2          py310hecd8cb5_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
python-json-logger        2.0.7           py310hecd8cb5_0  
pytorch                   1.13.1          cpu_py310h9e40b02_0  
pytz                      2023.3.post1    py310hecd8cb5_0  
pyyaml                    6.0.1           py310h6c40b1e_0  
pyzmq                     25.1.0          py310hcec6c5f_0  
qt-main                   5.15.2               h51e0635_8  
qt-webengine              5.15.9               h90a370e_7  
qtconsole                 5.4.2           py310hecd8cb5_0  
qtpy                      2.2.0           py310hecd8cb5_0  
qtwebkit                  5.212                hbfab81c_5  
re2                       2022.04.01           he9d5cce_0  
readline                  8.2                  hca72f7f_0  
regex                     2023.10.3       py310h6c40b1e_0  
requests                  2.31.0          py310hecd8cb5_0  
requests-oauthlib         1.3.0                      py_0  
rfc3339-validator         0.1.4           py310hecd8cb5_0  
rfc3986-validator         0.1.1           py310hecd8cb5_0  
rsa                       4.7.2              pyhd3eb1b0_1  
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.3.0           py310h3ea8b11_0  
scikit-surprise           1.1.3                    pypi_0    pypi
scipy                     1.11.3          py310ha516a68_0  
seaborn                   0.12.2                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                68.0.0          py310hecd8cb5_0  
sip                       6.6.2           py310he9d5cce_0  
six                       1.16.0             pyhd3eb1b0_1  
sklearn                   0.0.post5                pypi_0    pypi
snappy                    1.1.9                he9d5cce_0  
sniffio                   1.2.0           py310hecd8cb5_1  
soupsieve                 2.5             py310hecd8cb5_0  
sparse                    0.14.0                   pypi_0    pypi
sqlite                    3.41.2               h6c40b1e_0  
stack_data                0.2.0              pyhd3eb1b0_0  
surprise                  0.1                      pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tenacity                  8.2.2           py310hecd8cb5_0  
tensorboard               2.10.0          py310hecd8cb5_0  
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.10.0          eigen_py310haa97f9e_0  
tensorflow-base           2.10.0          eigen_py310h61e1807_0  
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-hub            0.13.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.32.0                   pypi_0    pypi
termcolor                 2.1.0           py310hecd8cb5_0  
terminado                 0.17.1          py310hecd8cb5_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tinycss2                  1.2.1           py310hecd8cb5_0  
tk                        8.6.12               h5d9f67b_0  
tokenizers                0.19.1                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py310hecd8cb5_0  
torch                     2.0.1                    pypi_0    pypi
torch-geometric           2.5.3                    pypi_0    pypi
torchdata                 0.6.1                    pypi_0    pypi
torchtext                 0.15.2                   pypi_0    pypi
tornado                   6.3.3           py310h6c40b1e_0  
tqdm                      4.65.0          py310h20db666_0  
traitlets                 5.7.1           py310hecd8cb5_0  
transformers              4.41.0                   pypi_0    pypi
typing-extensions         4.7.1           py310hecd8cb5_0  
typing_extensions         4.7.1           py310hecd8cb5_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.18         py310hecd8cb5_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py310hecd8cb5_1  
websocket-client          0.58.0          py310hecd8cb5_4  
werkzeug                  2.2.3           py310hecd8cb5_0  
wheel                     0.35.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.2           py310hecd8cb5_0  
wrapt                     1.14.1          py310hca72f7f_0  
x264                      1!157.20191217       h1de35cc_0  
xgboost                   1.7.3           py310hecd8cb5_0  
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.2                h6c40b1e_0  
yaml                      0.2.5                haf1e3a3_0  
yarl                      1.8.1           py310hca72f7f_0  
zeromq                    4.3.4                h23ab428_0  
zlib                      1.2.13               h4dc903c_0  
zstd                      1.5.5                hc035e20_0  
